# Environment Setup

This notebook demonstrates how to genotype recurrent CNVs. The only required input files is:
1. QCed CNV calls in .bed format: tab separated with header and first three columns: chrom, start, end.

The required tools are:
1. python (with pandas installed)
2. bedtools (code to install static binary below)

In [1]:
%%bash

wget -nv -O bedtools https://github.com/arq5x/bedtools2/releases/download/v2.28.0/bedtools
chmod a+x bedtools

2025-08-29 10:14:43 URL:https://release-assets.githubusercontent.com/github-production-release-asset/15059334/6cdff700-4d6a-11e9-9ddb-98618909f426?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-08-29T18%3A06%3A10Z&rscd=attachment%3B+filename%3Dbedtools&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-08-29T17%3A05%3A39Z&ske=2025-08-29T18%3A06%3A10Z&sks=b&skv=2018-11-09&sig=PIvI1rWn4t9qoTIj7W6Of%2BfuO8dsYQVs2McMDs0DQ%2FE%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc1NjQ4Nzg4MSwibmJmIjoxNzU2NDg3NTgxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.Vu-pugow3X69P7E3yOkS1qnbmOukvHSYzjzhvEAy31w&response-content-disposition=attachment%3B%20filename%3Dbedtools&response-content-type=application%2Foctet-stream [38962368/38962368] -> "bedtools" [1]

Next, set cohort name and date for saving output files.

In [2]:
import datetime
import os

# Set variables
COHORT = "UKBB"
TODAY = datetime.date.today().strftime("%Y-%m-%d")

# Optionally, export to environment variables for shell cells
os.environ["COHORT"] = COHORT
os.environ["TODAY"] = TODAY

# Read in and format locus definitions

The locus definitions are defined in this public spreadsheet: https://docs.google.com/spreadsheets/d/1v6bzdeFYorIJsjuBDSTdMDHQVU47IrLI/edit?pli=1&gid=1816231862#gid=1816231862

These blocks of code read in two sets of locus definitions:
1. Loci that are genotyped with 50% reciprocal overlap
2. Loci that are genotyped with 50% one-way overlap

Regions that have multiple adjacent or nested breakpoints are genotyped with one-way overlap

In [3]:
import pandas as pd

sheet_id = "1v6bzdeFYorIJsjuBDSTdMDHQVU47IrLI"  # your sheet ID
gid = "1816231862"  # sheet tab ID
url_reciprocal = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=tsv&gid={gid}'
df_reciprocal = pd.read_csv(url_reciprocal, sep="\t")

bed_reciprocal = df_reciprocal.loc[:,['CHR', 'START', 'END', 'Locus name']]
bed_reciprocal.to_csv('recurrentCNV_hg38.reciprocal.bed', index=False, sep='\t', header=False)
!head recurrentCNV_hg38.reciprocal.bed

hi
1	147056425	147922330	1q21.1
3	196011534	197617305	3q29
7	73331712	74715504	7q11.23_WBS
2	96076661	97011779	2q11.2
2	110105139	110226371	2q13_NPHP1
2	110636463	111255072	2q13
2	130723735	131173104	2q21.1
7	75508972	76435095	7q11.23_distal
10	48182156	49850750	10q11.21_11.23
10	80285716	87171894	10q22-23

In [4]:
sheet_id = "1v6bzdeFYorIJsjuBDSTdMDHQVU47IrLI"  # your sheet ID
gid = "1406215423"  # sheet tab ID
url_oneway = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=tsv&gid={gid}'

df_oneway = pd.read_csv(url_oneway, sep="\t")

bed_oneway = df_oneway.loc[:,['CHR', 'START', 'END', 'Locus name']]
bed_oneway.columns = ['locusCHR', 'locusSTART', 'locusEND', 'locusNAME']
bed_oneway.to_csv('recurrentCNV_hg38.oneway.bed', index=False, sep='\t', header=False)
!head recurrentCNV_hg38.oneway.bed

1	145627235	145809100	1q21.1_TAR_BP1_BP2
1	145823900	146040039	1q21.1_TAR_BP2_BP3
15	22778537	23067754	15q11.2_BP1_BP2
15	28917240	30083764	15q13.1-13.2_BP3_BP4
15	31724867	32170575	15q13.3_CHRNA7
16	15417798	16199832	16p13.11_BP1_BP2
16	16900000	18050000	16p13.11_BP2_BP3
16	21938814	22420568	16p12.2_BP2_BP3
16	28471892	28590813	16p11.2_BP1_BP2
16	28811875	29035462	16p11.2_BP2_BP3

# Reformat CNV calls

bedtools requires the first three columns of an input .bed file to be chromosome (column 1 in All Of Us "chrom"), start position (column 7, "consStart"), and end position (column 8, "consEnd"). We also need to include copy number (column 9, "consCallType") and sample ID (column 10, "sampleId").

All Of Us CNV calls are split into batches in a GCS bucket. This next block of code extracts the relevant columns and concatenates each batch. It also removes the "chr" prefix from the chromosome column

In [5]:
%%bash
output="${COHORT}.CNVcalls.consensus.${TODAY}.bed"
: > "$output"  # empty file

awk 'FNR>1 { sub(/^chr/, "", $1); print $1 "\t" $7 "\t" $8 "\t" $9 "\t" $10 }' Axiom.txt >> "$output"


head "$output"
ls -lh "$output"

10	27317506	27449073	DEL	1075
10	27319758	27405835	DEL	1016
10	66543042	66664234	DEL	GAU0098A
10	66543042	66664234	DEL	GAU0098C
10	84136380	84242965	DUP	GAU0100A
10	88373819	88536016	DEL	109665.1
1	102203589	102392983	DEL	11862FAT
1	105488006	105725768	DEL	107971.1
11	104177075	105432868	DUP	107187.1
11	106831729	107000380	DUP	104734.2
-rw-r--r-- 1 msacks ddp195 14M Aug 29 10:14 UKBB.CNVcalls.consensus.2025-08-29.bed

# Run bedtools with 50%  reciprocal overlap

In [6]:
%%bash

./bedtools intersect \
      -a recurrentCNV_hg38.reciprocal.bed \
      -b ${COHORT}.CNVcalls.consensus.${TODAY}.bed\
      -header -wb -wa -f .5 -r > ${COHORT}.reciprocal.${TODAY}.bed
      
head ${COHORT}.reciprocal.${TODAY}.bed
ls -lh ${COHORT}.reciprocal.${TODAY}.bed

1	147056425	147922330	1q21.1	1	147007226	147846731	DUP	4581197
1	147056425	147922330	1q21.1	1	147007226	147851425	DUP	5830725
1	147056425	147922330	1q21.1	1	147007226	147859786	DUP	2627226
1	147056425	147922330	1q21.1	1	147007226	147867836	DUP	3480258
1	147056425	147922330	1q21.1	1	147007226	147867836	DUP	4412977
1	147056425	147922330	1q21.1	1	147007226	147867836	DUP	5995402
1	147056425	147922330	1q21.1	1	147007226	147886242	DUP	5484756
1	147056425	147922330	1q21.1	1	147007226	147904926	DUP	3128949
1	147056425	147922330	1q21.1	1	147007226	147904926	DUP	3184495
1	147056425	147922330	1q21.1	1	147007226	147904926	DUP	3486958
-rw-r--r-- 1 msacks ddp195 329K Aug 29 10:14 UKBB.reciprocal.2025-08-29.bed

Read them into a pandas dataframe

In [7]:
reciprocal_calls = pd.read_csv(f'{COHORT}.reciprocal.{TODAY}.bed', sep='\t')
header = ['locusCHROM', 'locusSTART', 'locusEND', 'locusName', 'CHROM', 'START', 'END', 'TYPE', 'sampleID']
reciprocal_calls.columns = header
reciprocal_calls.head()

,locusCHROM,locusSTART,locusEND,locusName,CHROM,START,END,TYPE,sampleID
0,1,147056425,147922330,1q21.1,1,147007226,147851425,DUP,5830725
1,1,147056425,147922330,1q21.1,1,147007226,147859786,DUP,2627226
2,1,147056425,147922330,1q21.1,1,147007226,147867836,DUP,3480258
3,1,147056425,147922330,1q21.1,1,147007226,147867836,DUP,4412977
4,1,147056425,147922330,1q21.1,1,147007226,147867836,DUP,5995402

# Run bedtools with 50% one-way overlap

In [8]:
%%bash

./bedtools intersect \
      -a recurrentCNV_hg38.oneway.bed \
      -b ${COHORT}.CNVcalls.consensus.${TODAY}.bed\
      -header -wb -wa -f .5 > ${COHORT}.oneway.${TODAY}.bed
      
head ${COHORT}.oneway.${TODAY}.bed

1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	147768899	DUP	4864623
1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	147859786	DUP	5957245
1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	147911622	DUP	3627746
1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	147944014	DUP	1720902
1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	147944014	DUP	5411858
1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	147944014	DUP	3397587
1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	147944014	DUP	3325687
1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	147944014	DUP	4975493
1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	148317377	DUP	5376882
1	145627235	145809100	1q21.1_TAR_BP1_BP2	1	145430995	148338553	DUP	2663978

Read them into a pandas dataframe

In [9]:
oneway_calls = pd.read_csv(f'{COHORT}.oneway.{TODAY}.bed', sep='\t')
header = ['locusCHROM', 'locusSTART', 'locusEND', 'locusName', 'CHROM', 'START', 'END', 'TYPE', 'sampleID']
oneway_calls.columns = header
oneway_calls.head()

,locusCHROM,locusSTART,locusEND,locusName,CHROM,START,END,TYPE,sampleID
0,1,145627235,145809100,1q21.1_TAR_BP1_BP2,1,145430995,147859786,DUP,5957245
1,1,145627235,145809100,1q21.1_TAR_BP1_BP2,1,145430995,147911622,DUP,3627746
2,1,145627235,145809100,1q21.1_TAR_BP1_BP2,1,145430995,147944014,DUP,1720902
3,1,145627235,145809100,1q21.1_TAR_BP1_BP2,1,145430995,147944014,DUP,5411858
4,1,145627235,145809100,1q21.1_TAR_BP1_BP2,1,145430995,147944014,DUP,3397587

# Format calls into genotype matrix

For All Of Us, I initialized this matrix by reading in the manifest that includes sample QC ('Freq_Calc' column, formatted 1 for pass, 0 for fail). For other datasets, any matrix that contains one row for each sample ID (i.e. a sample manifest) works. Set the 'identifier' column to be the sampleIDs that match up with the CNV calls

In [10]:
sampleQC = '../ancestry/UKBB_manifest_20240805.txt'
genomatrix = pd.read_csv(sampleQC, sep="\t")
genomatrix['identifier'] = genomatrix['CNV_ID']
genomatrix.head()

/scratch/msacks/job_42278424/ipykernel_3099833/1008472197.py:2: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  genomatrix = pd.read_csv(sampleQC, sep="\t")

,SNP_Genotype_FID&IID,SNP_Genotype_FID,SNP_Genotype_IID,CNV_FID,CNV_ID,CNV_PID,CNV_MID,sex_famfile,gender_reported,sex_combined,...,SCZ,OCD,Manic,SZA,ASD,TS,ADHD,CASE,withdrawn_consent,identifier
0,1000014&1000014,1000014.0,1000014.0,NaN,1000014,NaN,NaN,2.0,F,2,...,0,0,0,0,0,0,0,0,no,1000014
1,1000023&1000023,1000023.0,1000023.0,NaN,1000023,NaN,NaN,1.0,M,1,...,0,0,0,0,0,0,0,0,no,1000023
2,1000030&1000030,1000030.0,1000030.0,NaN,1000030,NaN,NaN,1.0,M,1,...,0,0,0,0,0,0,0,0,no,1000030
3,1000041&1000041,1000041.0,1000041.0,NaN,1000041,NaN,NaN,2.0,F,2,...,0,0,0,0,0,0,0,0,no,1000041
4,1000059&1000059,1000059.0,1000059.0,NaN,1000059,NaN,NaN,2.0,F,2,...,0,0,0,0,0,0,0,0,no,1000059

Next, add reciprocal calls. You might have to change line 2 if your .bed file contained values other than 'DEL' and 'DUP'. For example, you might have 'deletion' and 'duplication', or 'loss' and 'gain'.

In [11]:
# Map CNV types to numeric codes
cn_mapping = {'DEL': 1, 'DUP': 3}
calls_df = reciprocal_calls.copy()
calls_df['CN'] = calls_df['TYPE'].map(cn_mapping)

# Get all unique loci
loci = calls_df['locusName'].unique()
loci_reciprocal = loci

# Ensure 'identifier' and 'sampleID' are string type for consistent merging
genomatrix['identifier'] = genomatrix['identifier'].astype(str)
calls_df['sampleID'] = calls_df['sampleID'].astype(str)

# Initialize columns in genomatrix_CNV with default value 2
for l in loci:
    genomatrix[l] = 2

# Pivot CNV calls to wide format (sample x locus)
pivoted = calls_df.pivot_table(index='sampleID', columns='locusName', values='CN', aggfunc='first')

# Merge CNV calls into genotype matrix using update
pivoted.index.name = 'identifier'  # match index name to merge key
genomatrix.set_index('identifier', inplace=True)
genomatrix.update(pivoted)
genomatrix.reset_index(inplace=True)

Next, add one-way calls. We add the suffix "oneway" to the locus names to indicate that these are not yet "allele specific". You might have to change line 2 if your .bed file contained values other than 'DEL' and 'DUP'. For example, you might have 'deletion' and 'duplication', or 'loss' and 'gain'.

In [12]:
# Map CNV types to numeric codes
cn_mapping = {'DEL': 1, 'DUP': 3}
calls_df = oneway_calls.copy()
calls_df['CN'] = calls_df['TYPE'].map(cn_mapping)

# Get all unique loci
loci = calls_df['locusName'].unique()
loci_oneway = [f'{l}_oneway' for l in loci]

# Ensure 'identifier' and 'sampleID' are string type for consistent merging
genomatrix['identifier'] = genomatrix['identifier'].astype(str)
calls_df['sampleID'] = calls_df['sampleID'].astype(str)
calls_df['locusName'] = calls_df['locusName'] + '_oneway'

# Initialize columns in genomatrix_CNV with default value 2
for l in loci:
    genomatrix[f'{l}_oneway'] = 2

# Pivot CNV calls to wide format (sample x locus)
pivoted = calls_df.pivot_table(index='sampleID', columns='locusName', values='CN', aggfunc='first')

# Merge CNV calls into genotype matrix using update
pivoted.index.name = 'identifier'  # match index name to merge key
genomatrix.set_index('identifier', inplace=True)
genomatrix.update(pivoted)
genomatrix.reset_index(inplace=True)
genomatrix.head()

,identifier,SNP_Genotype_FID&IID,SNP_Genotype_FID,SNP_Genotype_IID,CNV_FID,CNV_ID,CNV_PID,CNV_MID,sex_famfile,gender_reported,...,22q11.21_B_C_oneway,22q11.21_C_D_oneway,22q11.21_D_E_oneway,22q11.21_E_F_oneway,22q11.21_F_G_oneway,22q11.21_G_H_oneway,15q13.3_BP4_BP5_exclCHRNA7_oneway,16p12.2_BP1_BP2_oneway,15q11.2-13.1_BP2_BP3_oneway,16p11.2_BP3_BP4_oneway
0,1000014,1000014&1000014,1000014.0,1000014.0,NaN,1000014,NaN,NaN,2.0,F,...,2,2,2,2,2,2,2,2,2,2
1,1000023,1000023&1000023,1000023.0,1000023.0,NaN,1000023,NaN,NaN,1.0,M,...,2,2,2,2,2,2,2,2,2,2
2,1000030,1000030&1000030,1000030.0,1000030.0,NaN,1000030,NaN,NaN,1.0,M,...,2,2,2,2,2,2,2,2,2,2
3,1000041,1000041&1000041,1000041.0,1000041.0,NaN,1000041,NaN,NaN,2.0,F,...,2,2,2,2,2,2,2,2,2,2
4,1000059,1000059&1000059,1000059.0,1000059.0,NaN,1000059,NaN,NaN,2.0,F,...,2,2,2,2,2,2,2,2,2,2

Finally, add columns for loci that were not in your dataset (populate with 2s)

In [ ]:
!awk -F'\t' '{print $4}' recurrentCNV_hg38.reciprocal.bed > loci_names.txt
!awk -F'\t' '{print $4 "_oneway"}' recurrentCNV_hg38.oneway.bed >> loci_names.txt
with open('loci_names.txt') as f:
    loci = f.read().split('\n')

for l in loci:
    if l not in genomatrix.columns:
        genomatrix[l] = 2

# (Optional) set calls for samples that failed QC to NA

In [14]:
import numpy as np
all_loci = list(loci_oneway) + list(loci_reciprocal)
genomatrix.loc[genomatrix["NOTES..additional.filter.reason."] != 'pass', all_loci] = np.nan

# Combine one-way calls into "allele specific" genotypes

## 1q21.1 TAR

In [15]:
genomatrix['1q21.1_TAR_BP1_BP2'] = np.where(
    genomatrix['1q21.1_TAR_BP2_BP3_oneway'] == 2,
    genomatrix['1q21.1_TAR_BP1_BP2_oneway'],
    2
)

genomatrix['1q21.1_TAR_BP2_BP3'] = np.where(
    genomatrix['1q21.1_TAR_BP1_BP2_oneway'] == 2,
    genomatrix['1q21.1_TAR_BP2_BP3_oneway'],
    2
)

genomatrix['1q21.1_TAR_BP1_BP3'] = np.where(
    genomatrix['1q21.1_TAR_BP1_BP2_oneway'] == genomatrix['1q21.1_TAR_BP2_BP3_oneway'],
    genomatrix['1q21.1_TAR_BP2_BP3_oneway'],
    2
)

pd.crosstab(genomatrix['1q21.1_TAR_BP2_BP3'], genomatrix['1q21.1_TAR_BP1_BP2'])

1q21.1_TAR_BP1_BP2  1.0     2.0  3.0
1q21.1_TAR_BP2_BP3
1.0                   0       3    0
2.0                 233  487998   32
3.0                   0     111    0

## 15q11-13

This region has two separate CNV regions: BP1-3 and BP3-5. CNVs at CYFIP and CHRNA7 are common ( ~ 0.5% AF), so it is not unlikely that there are subjects who have one of these CNVs AND an independent CNV at the other end of the region. So, we genotype BP1-BP3 and BP3-BP5 independently

In [16]:
regions_15q13 = ['15q11.2_BP1_BP2_oneway', 
               '15q11.2-13.1_BP2_BP3_oneway']
genomatrix['15q13'] = (
    genomatrix[regions_15q13]
    .fillna(0)
    .astype(int)
    .astype(str)
    .agg(''.join, axis=1)
)

## 1-2 CYFIP

conditions = [
    genomatrix['15q13'] == '12',
    genomatrix['15q13'] == '32',
    genomatrix['15q13'] == '00'
]
choices = [1, 3, None]

genomatrix['15q11.2_BP1_BP2'] = np.select(conditions, choices, default=2)

## 2-3 

conditions = [
    genomatrix['15q13'] == '21',
    genomatrix['15q13'] == '23',
    genomatrix['15q13'] == '00'
]
choices = [1, 3, None]

genomatrix['15q11.2-13.1_BP2_BP3'] = np.select(conditions, choices, default=2)

## 1-3 

conditions = [
    genomatrix['15q13'] == '11',
    genomatrix['15q13'] == '33',
    genomatrix['15q13'] == '00'
]
choices = [1, 3, None]

genomatrix['15q11.2-13.1_BP1_BP3'] = np.select(conditions, choices, default=2)

pd.crosstab(genomatrix['15q11.2_BP1_BP2'], genomatrix['15q11.2-13.1_BP2_BP3'])

15q11.2-13.1_BP2_BP3  1       2   3
15q11.2_BP1_BP2
1                     0    1771   0
2                     1  344137  16
3                     0    2013   0

In [17]:
regions_15q35 = ['15q13.1-13.2_BP3_BP4_oneway',
               '15q13.3_BP4_BP5_exclCHRNA7_oneway',
               '15q13.3_CHRNA7_oneway']
genomatrix['15q35'] = (
    genomatrix[regions_15q35]
    .fillna(0)
    .astype(int)
    .astype(str)
    .agg(''.join, axis=1)
)

## 3-4 

conditions = [
    genomatrix['15q35'] == '122',
    genomatrix['15q35'] == '322',
    genomatrix['15q35'] == '000'
]
choices = [1, 3, None]

genomatrix['15q13.1-13.2_BP3_BP4'] = np.select(conditions, choices, default=2)

## 3-5 

conditions = [
    genomatrix['15q35'] == '111',
    genomatrix['15q35'] == '333',
    genomatrix['15q35'] == '000'
]
choices = [1, 3, None]

genomatrix['15q13.1-13.3_BP3_BP5'] = np.select(conditions, choices, default=2)

## 4-5 

conditions = [
    genomatrix['15q35'] == '211',
    genomatrix['15q35'] == '233',
    genomatrix['15q35'] == '000'
]
choices = [1, 3, None]

genomatrix['15q13.3_BP4_BP5'] = np.select(conditions, choices, default=2)

## 4-5 excl CHRNA7

conditions = [
    genomatrix['15q35'] == '212',
    genomatrix['15q35'] == '232',
    genomatrix['15q35'] == '000'
]
choices = [1, 3, None]

genomatrix['15q13.3_BP4_BP5_exclCHRNA7'] = np.select(conditions, choices, default=2)


## CHRNA7 

conditions = [
    genomatrix['15q35'] == '221',
    genomatrix['15q35'] == '223',
    genomatrix['15q35'] == '000'
]
choices = [1, 3, None]

genomatrix['15q13.3_CHRNA7'] = np.select(conditions, choices, default=2)


pd.crosstab(genomatrix['15q13.3_CHRNA7'], genomatrix['15q13.3_BP4_BP5'])

15q13.3_BP4_BP5   1       2    3
15q13.3_CHRNA7
1                 0       9    0
2                50  344481  265
3                 0    3133    0

## 16p11.2

In [18]:
regions_16p11 = ['16p11.2_BP1_BP2_oneway', 
                 '16p11.2_BP2_BP3_oneway', 
                 '16p11.2_BP3_BP4_oneway',
                 '16p11.2_BP4_BP5_oneway']
genomatrix['16p11.2'] = (
    genomatrix[regions_16p11]
    .fillna(0)
    .astype('int8')   # much smaller memory footprint
    .astype(str)
    .agg(''.join, axis=1)
)

## 1-2

conditions = [
    genomatrix['16p11.2'] == '1222',
    genomatrix['16p11.2'] == '3222',
    genomatrix['16p11.2'] == '0000'
]
choices = [1, 3, None]

genomatrix['16p11.2_BP1_BP2'] = np.select(conditions, choices, default=2)

## 1-3

conditions = [
    genomatrix['16p11.2'] == '1122',
    genomatrix['16p11.2'] == '3322',
    genomatrix['16p11.2'] == '0000'
]
choices = [1, 3, None]

genomatrix['16p11.2_BP1_BP3'] = np.select(conditions, choices, default=2)

## 2-3

conditions = [
    genomatrix['16p11.2'] == '2122',
    genomatrix['16p11.2'] == '2322',
    genomatrix['16p11.2'] == '0000'
]
choices = [1, 3, None]

genomatrix['16p11.2_BP2_BP3'] = np.select(conditions, choices, default=2)

## 3-4

conditions = [
    genomatrix['16p11.2'] == '2212',
    genomatrix['16p11.2'] == '2232',
    genomatrix['16p11.2'] == '0000'
]
choices = [1, 3, None]

genomatrix['16p11.2_BP3_BP4'] = np.select(conditions, choices, default=2)


## 4-5

conditions = [
    genomatrix['16p11.2'] == '2221',
    genomatrix['16p11.2'] == '2223',
    genomatrix['16p11.2'] == '0000'
]
choices = [1, 3, None]

genomatrix['16p11.2_BP4_BP5'] = np.select(conditions, choices, default=2)

pd.crosstab(genomatrix['16p11.2_BP4_BP5'], genomatrix['16p11.2_BP2_BP3'])

16p11.2_BP2_BP3   1       2    3
16p11.2_BP4_BP5
1                 0     127    0
2                58  347482  122
3                 0     149    0

## 16p12.2

In [19]:

genomatrix['16p12.2_BP1_BP2'] = np.where(
    genomatrix['16p12.2_BP2_BP3_oneway'] == 2,
    genomatrix['16p12.2_BP1_BP2_oneway'],
    2
)

genomatrix['16p12.2_BP2_BP3'] = np.where(
    genomatrix['16p12.2_BP1_BP2_oneway'] == 2,
    genomatrix['16p12.2_BP2_BP3_oneway'],
    2
)

genomatrix['16p12.2_BP1_BP3'] = np.where(
    genomatrix['16p12.2_BP1_BP2_oneway'] == genomatrix['16p12.2_BP2_BP3_oneway'],
    genomatrix['16p12.2_BP1_BP2_oneway'],
    2
)

pd.crosstab(genomatrix['16p12.2_BP1_BP2'], genomatrix['16p12.2_BP2_BP3'])

16p12.2_BP2_BP3  1.0     2.0  3.0
16p12.2_BP1_BP2
1.0                0     841    0
2.0              268  486979  208
3.0                0      81    0

## 16p13.3

In [20]:

genomatrix['16p13.11_BP1_BP2'] = np.where(
    genomatrix['16p13.11_BP2_BP3_oneway'] == 2,
    genomatrix['16p13.11_BP1_BP2_oneway'],
    2
)

genomatrix['16p13.11_BP2_BP3'] = np.where(
    genomatrix['16p13.11_BP1_BP2_oneway'] == 2,
    genomatrix['16p13.11_BP2_BP3_oneway'],
    2
)

genomatrix['16p13.11_BP1_BP3'] = np.where(
    genomatrix['16p13.11_BP1_BP2_oneway'] == genomatrix['16p13.11_BP2_BP3_oneway'],
    genomatrix['16p13.11_BP1_BP2_oneway'],
    2
)

pd.crosstab(genomatrix['16p13.11_BP1_BP2'], genomatrix['16p13.11_BP2_BP3'])

16p13.11_BP2_BP3  1.0     2.0  3.0
16p13.11_BP1_BP2
1.0                 0     124    0
2.0                 4  487523   14
3.0                 0     712    0

## 22q11.2

First, genotype the A-D region

In [21]:
regions_22qAD = ['22q11.21_A_B_oneway', '22q11.21_B_C_oneway', '22q11.21_C_D_oneway']
genomatrix['22q11.21_AD'] = (
    genomatrix[regions_22qAD]
    .fillna(0)
    .astype(int)
    .astype(str)
    .agg(''.join, axis=1)
)

## AB

conditions = [
    genomatrix['22q11.21_AD'] == '122',
    genomatrix['22q11.21_AD'] == '322',
    genomatrix['22q11.21_AD'] == '000',
]
choices = [1, 3, None]

genomatrix['22q11.21_A_B'] = np.select(conditions, choices, default=2)

## BC

conditions = [
    genomatrix['22q11.21_AD'] == '212',
    genomatrix['22q11.21_AD'] == '232',
    genomatrix['22q11.21_AD'] == '000',
]
choices = [1, 3, None]

genomatrix['22q11.21_B_C'] = np.select(conditions, choices, default=2)


## CD

conditions = [
    genomatrix['22q11.21_AD'] == '221',
    genomatrix['22q11.21_AD'] == '223',
    genomatrix['22q11.21_AD'] == '000',
]
choices = [1, 3, None]

genomatrix['22q11.21_C_D'] = np.select(conditions, choices, default=2)



## AC

conditions = [
    genomatrix['22q11.21_AD'] == '112',
    genomatrix['22q11.21_AD'] == '332',
    genomatrix['22q11.21_AD'] == '000',
]
choices = [1, 3, None]

genomatrix['22q11.21_A_C'] = np.select(conditions, choices, default=2)


## BD

conditions = [
    genomatrix['22q11.21_AD'] == '211',
    genomatrix['22q11.21_AD'] == '233',
    genomatrix['22q11.21_AD'] == '000',
]
choices = [1, 3, None]

genomatrix['22q11.21_B_D'] = np.select(conditions, choices, default=2)


## AD

conditions = [
    genomatrix['22q11.21_AD'] == '111',
    genomatrix['22q11.21_AD'] == '333',
    genomatrix['22q11.21_AD'] == '000',
]
choices = [1, 3, None]

genomatrix['22q11.21_A_D'] = np.select(conditions, choices, default=2)


## note, there were some samples with 323... this is likely due to a fragmented call

pd.crosstab(genomatrix['22q11.21_A_D'], genomatrix['22q11.21_B_D'])

22q11.21_B_D   1       2    3
22q11.21_A_D
1              0       5    0
2             15  347518  117
3              0     283    0

Next, genotype the D-H region

In [22]:
regions_22qDH = ['22q11.21_D_E_oneway','22q11.21_E_F_oneway', 
                 '22q11.21_F_G_oneway', '22q11.21_G_H_oneway']

genomatrix['22q11.21_DH'] = (genomatrix[regions_22qDH]
    .fillna(0)
    .astype(int)
    .astype(str)
    .agg(''.join, axis=1)
                           )

## DE

conditions = [
    genomatrix['22q11.21_DH'] == '1222',
    genomatrix['22q11.21_DH'] == '3222',
    genomatrix['22q11.21_DH'] == '0000'
]
choices = [1, 3, None]

genomatrix['22q11.21_D_E'] = np.select(conditions, choices, default=2)


## EF

conditions = [
    genomatrix['22q11.21_DH'] == '2122',
    genomatrix['22q11.21_DH'] == '2322',
    genomatrix['22q11.21_DH'] == '0000'
]
choices = [1, 3, None]

genomatrix['22q11.21_E_F'] = np.select(conditions, choices, default=2)


## FG

conditions = [
    genomatrix['22q11.21_DH'] == '2212',
    genomatrix['22q11.21_DH'] == '2232',
    genomatrix['22q11.21_DH'] == '0000'
]
choices = [1, 3, None]


genomatrix['22q11.21_F_G'] = np.select(conditions, choices, default=2)

## GH

conditions = [
    genomatrix['22q11.21_DH'] == '2221',
    genomatrix['22q11.21_DH'] == '2223',
    genomatrix['22q11.21_DH'] == '0000'
]
choices = [1, 3, None]

genomatrix['22q11.21_G_H'] = np.select(conditions, choices, default=2)

## FH

conditions = [
    genomatrix['22q11.21_DH'] == '2211',
    genomatrix['22q11.21_DH'] == '2233',
    genomatrix['22q11.21_DH'] == '0000'
]
choices = [1, 3, None]
genomatrix['22q11.21_F_H'] = np.select(conditions, choices, default=2)

## EH

conditions = [
    genomatrix['22q11.21_DH'] == '2111',
    genomatrix['22q11.21_DH'] == '2333',
    genomatrix['22q11.21_DH'] == '0000'
]
choices = [1, 3, None]
genomatrix['22q11.21_E_H'] = np.select(conditions, choices, default=2)

## DH

conditions = [
    genomatrix['22q11.21_DH'] == '1111',
    genomatrix['22q11.21_DH'] == '3333',
    genomatrix['22q11.21_DH'] == '0000'
]
choices = [1, 3, None]
genomatrix['22q11.21_D_H'] = np.select(conditions, choices, default=2)


pd.crosstab(genomatrix['22q11.21_D_E'], genomatrix['22q11.21_F_H'])

22q11.21_F_H  1       2    3
22q11.21_D_E
1             0       3    0
2             1  347762  170
3             0       2    0

# View table of counts for each CNV

In [33]:
allloci = [a[:-7] if a[-6:] == 'oneway' else a for a in all_loci] + list(genomatrix.columns)[-40:]
allloci = list(set(allloci))
table = []

for l in allloci:
    row = {"locus": l}
    if 1 in genomatrix[l].value_counts():
        row['n_DELs'] = genomatrix[l].value_counts()[1]
    else:
        row['n_DELs'] = 0
      
    if 3 in genomatrix[l].value_counts():
        row['n_DUPs'] = genomatrix[l].value_counts()[3]
    else:
        row['n_DUPs'] = 0
    table.append(row)
    
counts = pd.DataFrame(table).sort_values(by='n_DUPs', ascending=False)
pd.set_option('display.max_rows', None)
counts

                         locus  n_DELs  n_DUPs
34              15q13.3_CHRNA7       9    3133
17             15q11.2_BP1_BP2    1771    2013
38                  2q13_NPHP1    2696    1022
30            16p13.11_BP1_BP2     124     712
24          1q21.1_TAR_BP1_BP3     103     356
33                22q11.21_A_D       5     283
23             15q13.3_BP4_BP5      50     265
40                    13q12.12      86     252
7              16p12.2_BP2_BP3     268     208
8             16p13.11_BP1_BP3      20     201
45                22q11.21_F_H       1     170
0              16p11.2_BP4_BP5     127     149
18                       17p12     274     140
35             16p11.2_BP2_BP3      58     122
51                      1q21.1      93     121
43                22q11.21_B_D      15     117
1           1q21.1_TAR_BP2_BP3       3     111
26                       17q12      10     106
21                22q11.21_C_D      22      92
32             16p12.2_BP1_BP2     841      81
49                      2q21.1      46      64
36        15q13.1-13.2_BP3_BP4      20      60
48                22q11.21_E_F      44      51
3                       2q11.2      35      33
44          1q21.1_TAR_BP1_BP2     233      32
14              7q11.23_distal       1      26
37                22q11.21_A_B       5      24
39                22q11.21_F_G       1      23
25                 7q11.23_WBS       1      17
27              10q11.21_11.23      43      16
50        15q11.2-13.1_BP2_BP3       1      16
19            16p13.11_BP2_BP3       4      14
28                22q11.21_B_C       0      12
20                    10q22-23       3       9
13                22q11.21_G_H       2       9
12        15q13.1-13.3_BP3_BP5       1       9
16             16p11.2_BP1_BP2       2       8
47             16p11.2_BP1_BP3       0       6
29                22q11.21_A_C       0       6
41             16p12.2_BP1_BP3       2       3
42                        3q29       9       3
46        15q11.2-13.1_BP1_BP3       0       3
6                         2q13      12       2
4                 22q11.21_D_E       3       2
22                     17p11.2       1       2
11  15q13.3_BP4_BP5_exclCHRNA7       0       2
15             16p11.2_BP3_BP4       0       0
10                 22q11.21_DH       0       0
2                        15q35       0       0
5                        15q13       0       0
9                  22q11.21_AD       0       0
31                     16p11.2       0       0

# Write output

In [24]:

genomatrix.to_csv(f'genomatrix.recurrentCNV.{TODAY}.csv')